### ISSUE TITLE
Twitter sidebar is waaaaaay too long

### ISSUE THREAD

**Issue by albertodainotti** [InetIntel/ioda-ui#66]
I believe it used to have a scroll bar. What happened?

![Screen Shot 2022-08-19 at 6 16 39 PM](https://user-images.githubusercontent.com/9420859/185714205-a05bab82-9ba8-438e-b764-cf6da49cc8f6.png)

**Comment by data-101** [comment]
Seems to be an issue due to changes in twitter API propagated to us from the 3rd party library we use(GitHub issue: https://github.com/saurabhnemade/react-twitter-embed/issues/116)
