### ISSUE TITLE
GTR Data for Congo - Brazzaville and Congo Kinshasa

### ISSUE THREAD

**Issue by amandahmeng** [InetIntel/ioda-ui#91]
Looks like maybe GTR has changed some country names/codes? Congo and DRC stopped showing google product traffic on April 19th. When I look at google product traffic on the GTR site they have traffic for Congo - Brazzaville and Congo Kinshasa
Congo in IODA: https://ioda.inetintel.cc.gatech.edu/country/CG?from=1681448400&until=1682139599
DRC in IODA: https://ioda.inetintel.cc.gatech.edu/country/CD?from=1681448400&until=1682139599

Link to Congo - Kinshasa in GTR:
[[https://transparencyreport.google.com/traffic/overview?hl=en&fraction_traffic=start:1679443[…]1682121599999;product:19;region:CD&lu=fraction_traffic](https://transparencyreport.google.com/traffic/overview?hl=en&fraction_traffic=start:1679443200000;end:1682121599999;product:19;region:CD&lu=fraction_traffic)](https://transparencyreport.google.com/traffic/overview?hl=en&fraction_traffic=start:1679443200000;end:1682121599999;product:19;region:CD&lu=fraction_traffic)

**Comment by salcock** [comment]
The GTR data scraper had stopped fetching data for some reason. I've restarted it and everything should be working again.
